export interface BodyMeasurements {
  bust?: number;
  waist?: number;
  hips?: number;
  inseam?: number;
  torsoLength?: number;
  [key: string]: number | undefined; // Flexible for varied clothing types
}

export interface PatternCoordinates {
  // Array of SVG path points or instructions generated by your math formulas
  nodes: { id: string; x: number; y: number; label: string }[];
  paths: { d: string; type: 'cut' | 'sew' | 'grainline' }[];
  dimensions: { width: number; height: number };
}

export interface Project {
  id: string;
  created_by: string;
  created_at: string;
  updated_at: string;
  clothing_type: string;
  status: 'uploaded' | 'processing' | 'completed';
  original_image_url?: string;
  refined_image_url?: string;
  measurements: BodyMeasurements;
  pattern_data: PatternCoordinates;
  is_public: boolean;
  title: string;
  description?: string;
  likes: number;
}
